config/routes.rb
Rails.application.routes.draw do
  resources :cashflows
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cashflows#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashflow.rb
class Cashflow < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cashflows

  before_save :default_values
  def default_values
    self.balance = '0' if self.balance.nil? # sets the balance to 0 for each if no value was specified.
  end

  def balance
    cashflows.sum(&:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cashflows_controller.rb
class CashflowsController < ApplicationController
  before_action :set_cashflow, only: [:show, :edit, :update, :destroy]

  # GET /cashflows
  # GET /cashflows.json
  def index
    @cashflows = Cashflow.all
  end

  # GET /cashflows/1
  # GET /cashflows/1.json
  def show
  end

  # GET /cashflows/new
  def new
    @cashflow = Cashflow.new
  end

  # GET /cashflows/1/edit
  def edit
  end

  # POST /cashflows
  # POST /cashflows.json
  def create
    @cashflow = Cashflow.new(cashflow_params)

    respond_to do |format|
      if @cashflow.save
        format.html { redirect_to @cashflow, notice: 'Cashflow was successfully created.' }
        format.json { render :show, status: :created, location: @cashflow }
      else
        format.html { render :new }
        format.json { render json: @cashflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashflows/1
  # PATCH/PUT /cashflows/1.json
  def update
    respond_to do |format|
      if @cashflow.update(cashflow_params)
        format.html { redirect_to @cashflow, notice: 'Cashflow was successfully updated.' }
        format.json { render :show, status: :ok, location: @cashflow }
      else
        format.html { render :edit }
        format.json { render json: @cashflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashflows/1
  # DELETE /cashflows/1.json
  def destroy
    @cashflow.destroy
    respond_to do |format|
      format.html { redirect_to cashflows_url, notice: 'Cashflow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cashflow
      @cashflow = Cashflow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cashflow_params
      params.require(:cashflow).permit(:amount, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :balance, :address, :phone, :email, :accountinfo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashflows_helper.rb
module CashflowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cashflows/_form.html.erb
<%= form_with(model: cashflow, local: true) do |form| %>
  <% if cashflow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cashflow.errors.count, "error") %> prohibited this cashflow from being saved:</h2>

      <ul>
      <% cashflow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :cashflow_amount %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :cashflow_description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.order(:name),:id,:name, include_blank: false %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cashflows/edit.html.erb
<h1>Editing Cashflow</h1>

<%= render 'form', cashflow: @cashflow %>

<%= link_to 'Show', @cashflow %> |
<%= link_to 'Back', cashflows_path %>

app/views/cashflows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cashflows</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Description</th>
      <th>User</th>
      <th>Timestamp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cashflows.each do |cashflow| %>
      <tr>
        <td><%= cashflow.amount %></td>
        <td><%= cashflow.description %></td>
        <td><%= cashflow.user.name %></td>
        <td><%= cashflow.updated_at %></td>
        <td><%= link_to 'Show', cashflow %></td>
        <td><%= link_to 'Edit', edit_cashflow_path(cashflow) %></td>
        <td><%= link_to 'Destroy', cashflow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cashflow', new_cashflow_path %>

app/views/cashflows/new.html.erb
<h1>New Cashflow</h1>

<%= render 'form', cashflow: @cashflow %>

<%= link_to 'Back', cashflows_path %>

app/views/cashflows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @cashflow.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cashflow.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @cashflow.user.name %>
</p>

<%= link_to 'Edit', edit_cashflow_path(@cashflow) %> |
<%= link_to 'Back', cashflows_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Financier</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav>
    <a href="/cashflows">Cashflows</a>
    <a href="/users">Users</a>
  </nav>

  <body>
  	<div class="site-wrap">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :user_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :user_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :accountinfo %>
    <%= form.text_area :accountinfo, id: :user_accountinfo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Balance</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Accountinfo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.balance %></td>
        <td><%= user.address %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.accountinfo %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @user.balance %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Accountinfo:</strong>
  <br/><%= @user.accountinfo %>
</p>

<p>
  <em><strong>Cashflow Feed</strong></em>
  <% @user.cashflows.each do |cashflow| %>
    <br/>Timestamp: <%= cashflow.updated_at %>
    <br/>Amount: <%= cashflow.amount %> 
    <br/>Description: <%= cashflow.description %>
    <br/>
  <% end %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>